###
#  KITTY CONFIGURATION FILE 4 of 4
#  https://github.com/snes19xx
####

# --- Typography ---
font_family      CMU Typewriter Text Variable Width
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.5

# --- Window Layout & Padding ---
placement_strategy top-left
window_padding_width 0 12 12 12
hide_window_decorations yes
confirm_os_window_close 0

# --- Cursor ---
cursor_shape underline
cursor_underline_thickness 2.0
cursor_blink_interval 0

# --- Tab Bar ---
tab_bar_edge top
tab_bar_style separator
tab_separator " │ "
tab_bar_min_tabs 1
tab_bar_show_new_tab_button yes
tab_bar_align right
tab_bar_margin_height 0.0 0.0

# Minimal template with a close indicator
tab_title_template " {index}: {title}"

# Mouse mappings for easy closing
mouse_map middle click grabbed,ungrabbed close_tab
mouse_map right click grabbed,ungrabbed close_tab

# --- Active/Inactive Tab Colors ---
active_tab_foreground   #1c1c1c
active_tab_background   #5790fe
active_tab_font_style   bold
inactive_tab_foreground #cfd2d5
inactive_tab_background #3d3e40
inactive_tab_font_style normal
tab_bar_background      #1c1c1c

# --- Color Scheme (Darcula Solid) ---
background  #323335
foreground  #cfd2d5

cursor                #f7f7f7

selection_foreground  #cfd2d5
selection_background  #176081

color0  #1c1c1c
color8  #8a8a8a

# red
color1                #ff5b56
color9                #c95942

# green
color2                #5af78d
color10               #89d957

# yellow
color3                #ffc24b
color11               #f7bb3b

# blue
color4                #5790fe
color12               #6897BB

# magenta
color5                #a782bb
color13               #c955ae

# cyan
color6                #5ed5ed
color14               #75e7ff

# light gray / dark gray
color7                #b8b8b8
color15               #f1f1f0

# --- Performance & System (Wayland Optimization) ---
linux_display_server wayland
repaint_delay 8
input_delay 2
sync_to_monitor yes
