## name: Silverhand
## blurb: A silverhand theme based on the Cyberpunk VIM Colorscheme by thedenisnikulin.

#: The basic colors

foreground                      #EDF37E
background                      #101116
selection_foreground            none
selection_background            #19213B


#: Cursor colors

cursor                          #00FFC8
cursor_text_color               background


#: URL underline color when hovering with mouse

url_color                       #FFFC58


#: kitty window border colors and terminal bell colors

active_border_color             #5E81F5
inactive_border_color           #2B3E5A
bell_border_color               #FF0055
visual_bell_color               none


#: Tab bar colors

active_tab_foreground           #101116
active_tab_background           #FF4081
inactive_tab_foreground         #FF4081
inactive_tab_background         #101116
tab_bar_background              #070811
tab_bar_margin_color            #070811


#: The basic 16 colors

#: black
color0  #000000
color8  #6766B3

#: red
color1  #FF1745
color9  #FF3270

#: green
color2  #009550
color10 #00FF9C

#: yellow
color3  #EDF37E
color11 #FFFC58

#: blue
color4  #5E81F5
color12 #00B0FF

#: magenta
color5  #C592FF
color13 #D57BFF

#: cyan
color6  #00FFC8
color14 #8AEBF1

#: white
color7  #EEFFFF
color15 #FFFFFF
